version: "2"
services:
  backend:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
  
  client:
    build: ./client
    tty: true
    stdin_open: true
    links:
      - backend
  
  admin-app:
    build: ./admin_app
    links:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
