version: "3.3"
volumes:
  prometheus_volume: {}
services:
  backend:
    image: alexfazakas/backend
    ports:
      - "5000:5000"
    hostname: backend
  
  client:
    image: alexfazakas/client
    tty: true
    stdin_open: true
  
  matchups:
    image: alexfazakas/matchups
    ports:
      - "5001:5001"
    hostname: matchups

  db:
    image: alexfazakas/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
